# Generated by Django 4.1.7 on 2023-04-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
