# Generated by Django 4.1.7 on 2023-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='img',
            field=models.FileField(upload_to='people/'),
        ),
    ]
