# Generated by Django 4.2 on 2023-05-02 16:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_people_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publication_Title', models.CharField(default='', max_length=200)),
                ('abstract', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('DOI', models.CharField(default='', max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
                ('Author', models.ManyToManyField(default='', to='users.people')),
            ],
            options={
                'verbose_name': 'Publications',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
