# Generated by Django 4.2 on 2023-05-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, unique=True)),
                ('dsgOrder', models.CharField(default='', max_length=3, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Faculty designation',
                'verbose_name_plural': 'Faculty designations',
                'ordering': ['-dsgOrder'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_topic', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=250)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Research Topics',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.publicationcategory', verbose_name='PublicationCategory'),
        ),
    ]
