# Generated by Django 4.2 on 2023-05-03 12:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_designation_researchtopic_people_total_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='FullName',
        ),
        migrations.AddField(
            model_name='people',
            name='BanglaName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='LoginUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Select your E-mail'),
        ),
        migrations.AddField(
            model_name='people',
            name='Professional_Certifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='academic_Background',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='award',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='conference_Papers',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='google_ScholarLink',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='journal_Papers',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='leav_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Leave status(any if)'),
        ),
        migrations.AddField(
            model_name='people',
            name='officeBuilding',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='office_Phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='office_RoomNo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='people',
            name='other_Contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='professional_international_work',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='professional_membership',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='researchArea',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='researchGrant',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='research_Gate_Link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='research_Interest',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='research_Topic',
            field=models.ManyToManyField(blank=True, default='', null=True, to='users.researchtopic'),
        ),
        migrations.AddField(
            model_name='people',
            name='selected_Publications',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Book_Chapter'),
        ),
        migrations.AddField(
            model_name='people',
            name='teachingArea',
            field=models.CharField(blank=True, max_length=200, verbose_name='Teaching Area'),
        ),
        migrations.AddField(
            model_name='people',
            name='teachingExprience',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='people',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.designation', verbose_name='Designation'),
        ),
    ]
