# Generated by Django 4.2 on 2023-05-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_projectcategory_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['seniority_order'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RenameField(
            model_name='people',
            old_name='award',
            new_name='AwardAndResearchGrant',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='office_Phone',
            new_name='GitHub_link',
        ),
        migrations.RemoveField(
            model_name='people',
            name='leav_status',
        ),
        migrations.RemoveField(
            model_name='people',
            name='officeBuilding',
        ),
        migrations.RemoveField(
            model_name='people',
            name='office_RoomNo',
        ),
        migrations.RemoveField(
            model_name='people',
            name='researchArea',
        ),
        migrations.RemoveField(
            model_name='people',
            name='researchGrant',
        ),
        migrations.RemoveField(
            model_name='people',
            name='research_Interest',
        ),
        migrations.RemoveField(
            model_name='people',
            name='selected_Publications',
        ),
        migrations.RemoveField(
            model_name='people',
            name='teachingArea',
        ),
        migrations.RemoveField(
            model_name='people',
            name='teachingExprience',
        ),
        migrations.AddField(
            model_name='people',
            name='Kaggle_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='LinkedIn_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='people',
            name='seniority_order',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='people',
            name='research_Topic',
            field=models.ManyToManyField(blank=True, null=True, to='users.researchtopic'),
        ),
    ]
