# Generated by Django 4.2 on 2023-05-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_people_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(blank=True, upload_to='LetestNews/pdf/')),
                ('photo', models.ImageField(blank=True, upload_to='LetestNews/photo/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(verbose_name='On Date')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
            ],
        ),
    ]
