# Generated by Django 4.2 on 2023-05-04 08:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_letestnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letestnews',
            options={'ordering': ['-created_on'], 'verbose_name': 'News', 'verbose_name_plural': 'LetestNews'},
        ),
        migrations.AddField(
            model_name='letestnews',
            name='Details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
