# Generated by Django 4.2 on 2023-05-04 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
