# Generated by Django 4.2 on 2023-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_researchunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='researchUnit',
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='short_bio',
            field=models.TextField(default=''),
        ),
    ]
