# Generated by Django 4.2 on 2023-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_researchunit_researchtopic_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='research_Topic',
            field=models.ManyToManyField(blank=True, to='users.researchtopic'),
        ),
    ]
