# Generated by Django 4.2 on 2023-06-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_people_research_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchtopic',
            name='short_bio',
            field=models.CharField(default='', max_length=500),
        ),
    ]
