# Generated by Django 4.2 on 2023-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_researchtopic_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
