# Generated by Django 4.2 on 2023-07-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_people_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='abstract',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='DOI',
        ),
    ]
