# Generated by Django 4.2 on 2023-11-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_resurachunit_designation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='category',
            field=models.CharField(choices=[('Founder & Research Director', 'Founder & Research Director'), ('Advisor', 'Advisor'), ('Research Associates', 'Research Associates'), ('Research Coordinator & Lead R.A', 'Research Coordinator & Lead R.A'), ('Research Assistants', 'Research Assistants'), ('Research Intern', 'Research Intern'), ('Alumni', 'Alumni')], default='research_student', max_length=100),
        ),
    ]
