# Generated by Django 4.2 on 2023-11-27 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_researchtopic_de_alter_people_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchtopic',
            name='de',
        ),
        migrations.CreateModel(
            name='ResearchAreaPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resurachunit_designation')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.people')),
                ('research_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.researchtopic')),
            ],
        ),
    ]
