# Generated by Django 4.2 on 2023-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_researchtopic_de_researchareapeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='RU_Designation',
        ),
        migrations.AlterField(
            model_name='people',
            name='category',
            field=models.CharField(choices=[('Founder & Research Director', 'Founder & Research Director'), ('Advisor', 'Advisor'), ('Head of the Department', 'Head of the Department'), ('Lead Researcher', 'Lead Researcher'), ('Researcher', 'Researcher'), ('Research Assistant', 'Research Assistant'), ('Research Intern', 'Research Intern'), ('Alumni', 'Alumni')], default='research_student', max_length=100),
        ),
    ]
