# Generated by Django 4.2 on 2023-12-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_people_ru_designation_alter_people_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, default='', max_length=250)),
                ('CatOrder', models.IntegerField(default='', unique=True)),
                ('slug', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'People Category',
                'verbose_name_plural': 'People Categorys',
                'ordering': ['CatOrder'],
            },
        ),
        migrations.AddField(
            model_name='publications',
            name='publish_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='people',
            name='category',
        ),
        migrations.AddField(
            model_name='people',
            name='category',
            field=models.ManyToManyField(blank=True, to='users.peoplecategory'),
        ),
    ]
