# Generated by Django 4.2 on 2023-12-02 19:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_peoplecategory_publications_publish_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, default='', upload_to='Achivements/')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(verbose_name='On Date')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Achivement Publication',
                'verbose_name_plural': 'Achivement Publications',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='AdminCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, unique=True)),
                ('dsgOrder', models.CharField(blank=True, default='', max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Admin Committee',
                'verbose_name_plural': 'Admin Committees',
            },
        ),
        migrations.CreateModel(
            name='MissionAMIRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mission of AMIR Lab',
                'verbose_name_plural': 'Mission of AMIR Lab',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='VisionAMIRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vision of AMIR Lab',
                'verbose_name_plural': 'Vision of AMIR Lab',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='WhyatAMIRL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why at AMIRL',
                'verbose_name_plural': 'Why at AMIRL',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='AdminCommitteeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('total_views', models.IntegerField(default=0)),
                ('Committee', models.ManyToManyField(default='', to='users.admincommittee', verbose_name='Admin Committee Name')),
                ('MemberName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.people', verbose_name='Admin Committee Name')),
            ],
        ),
    ]
