# Generated by Django 4.2 on 2023-12-06 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_achivements_admincommittee_missionamirl_visionamirl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('CurrentAffiliations', models.TextField(choices=[('Student', 'Student'), ('Work', 'Work'), ('Others', 'Others')], max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('PreviousExperience', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('accepted', models.BooleanField(default=False)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('InterestedResearchTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.researchtopic')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.resurachunit_designation')),
            ],
        ),
    ]
